FROM tomoncle/java:oracle-1.8.0
MAINTAINER tomoncle <tomoncle@sina.com>

#COPY target/powerjob-worker-simple.jar /opt/app.jar
COPY src/main/resources                /opt/config

EXPOSE 8082

#CMD ["java", "-jar", "/opt/app.jar"]
