name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setting an environment variable
        id: step_one
        run: |
          echo "action_state=yellow" >> "${GITHUB_ENV}"

      - name: Use the environment variable
        id: step_two
        run: |
          printf '%s\n' "${action_state}" # This will output 'yellow'

      - name: Test with Maven
        run: mvn clean test

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Get version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> "${GITHUB_ENV}"

      ## https://github.com/docker/login-action
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ## https://github.com/docker/build-push-action
      - name: Docker Build & Push
        uses: docker/build-push-action@v5
        with:
          ## docker build -t test -f ./powerjob-worker-simple/Dockerfile ./powerjob-worker-simple
          context: ./powerjob-worker-simple
          # platforms: linux/amd64,linux/arm64/v8
          file: ./powerjob-worker-simple/Dockerfile
          push: true
          tags: |
            tomoncle/powerjob-worker-simple:latest
            tomoncle/powerjob-worker-simple:dev

      - name: Docker Image Check Digest
        run: |
          docker manifest inspect --verbose tomoncle/powerjob-worker-simple
          echo "Git Tag ==> 自定义变量：${VERSION}, 内置变量：${{ github.ref }}"

